
const USERS=[{"name": "Daniel", "user": "cookjdan"}, {"name": "Trezevant", "user": "trezevga"}, {"name": "Larry", "user": "klarjack"}, {"name": "Marvin", "user": "bermarv"}, {"name": "Jason", "user": "millrov"}, {"name": "Arshon", "user": "arshoben"}, {"name": "Christon", "user": "bealchr"}, {"name": "Christipher", "user": "chlewisb"}, {"name": "Darnell", "user": "darlgibs"}, {"name": "Darrion", "user": "dccarabi"}, {"name": "James", "user": "jamsv"}, {"name": "Jason O.", "user": "jasoocon"}, {"name": "Jim", "user": "jiwlli"}, {"name": "Micheal", "user": "mmichhas"}, {"name": "Randall", "user": "gooranda"}];const $=s=>document.querySelector(s);
const ls={get:(k,v)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(v))}catch{return v}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const nowISO=()=>new Date().toISOString();
const state=ls.get('pd_state_v7',{shiftGroup:'',techsSelected:[],techManual:'',startTT:'',endTT:'',partsUsed:'N/A',safetyTip:'',tipMode:'pro',techMode:false,channelNote:'#passdown',reminderMin:120,dark:'auto',logs:[],lastExportWeekEnd:'',photos:[],tips:{pro:["Use PPE appropriate to the task; verify fit before starting.","Maintain three points of contact on stairs and ladders.","Report spills and trip hazards immediately and block off area.","Secure laces, jewelry, and clothing near moving machinery.","Lift with legs; keep load close; team-lift heavy items.","Lockout/Tagout before servicing. Verify zero energy state.","Review SDS before handling chemicals; store properly.","Hydrate and take micro-breaks to reduce strain.","Inspect tools before use; tag out damaged equipment.","Keep exits and aisles clear; stage parts in designated zones.","Use the right ladder height; do not stand on top step.","Wear hearing protection in high-noise areas.","Bleed pressure before disconnecting air lines.","Verify isolation before removing guards; reattach after work.","Confirm equipment returns to normal parameters after repair."],petty:["Tie your shoes. Falling hurts more when getting up takes all morning.","Use the handrail — stairs are undefeated since forever.","Wear PPE. Squinting is not eye protection.","Shortcuts? Fun until your name trends in the incident log.","Lift with your legs — your back already filed for retirement.","If it smells weird, don’t taste-test it. Not a cooking show.","Hear a pop? Stop. Whether it’s your knee or the machine, neither is happy.","Clean as you go — tripping on your own mess is a career lowlight.","Gloves are cheaper than stitches. Your call.","Lockout beats luck-out. Choose wisely."]}}});
function save(){ls.set('pd_state_v7',state)}
function applyTheme(){let m=state.dark;if(m==='auto')m=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.dataset.theme=m}applyTheme();
$('#btn-dark').onclick=()=>{state.dark=document.documentElement.dataset.theme==='dark'?'light':'dark';save();applyTheme()};
function drawTechs(f=''){const list=$('#techList');list.innerHTML='';USERS.filter(u=>(u.name+' '+u.user).toLowerCase().includes(f.toLowerCase())).forEach(u=>{const id='tech_'+u.user;const row=document.createElement('label');row.className='item';row.innerHTML=`<input type="checkbox" id="${id}" data-user="${u.user}" data-name="${u.name}"> <span>${u.name} (@${u.user})</span>`;const cb=row.querySelector('input');cb.checked=state.techsSelected.some(t=>t.user===u.user);cb.onchange=()=>{if(cb.checked)state.techsSelected.push({name:u.name,user:u.user});else state.techsSelected=state.techsSelected.filter(t=>t.user!==u.user);save();drawTechs(f);drawChips();render()};list.appendChild(row)})}
function drawChips(){const chips=$('#techChips');chips.innerHTML='';state.techsSelected.forEach(t=>{const el=document.createElement('span');el.className='chip';el.innerHTML=`${t.name} (@${t.user}) <button aria-label="remove">&times;</button>`;el.querySelector('button').onclick=()=>{state.techsSelected=state.techsSelected.filter(x=>x.user!==t.user);save();drawTechs($('#techSearch').value);drawChips();render()};chips.appendChild(el)})}
$('#techSearch').oninput=e=>drawTechs(e.target.value);drawTechs('');drawChips();
function renderPhotos(){const w=$('#photoPreview');w.innerHTML='';state.photos.forEach((s,i)=>{const img=new Image();img.src=s;img.alt='photo '+(i+1);w.appendChild(img)})}
$('#photoInput').onchange=async e=>{const files=[...(e.target.files||[])];for(const f of files){const r=new FileReader();const p=new Promise((res,rej)=>{r.onload=()=>res(r.result);r.onerror=rej});r.readAsDataURL(f);state.photos.push(await p)}save();renderPhotos();render()};
$('#btnClearPhotos').onclick=()=>{state.photos=[];save();renderPhotos();render()};
function randomTip(){const a=state.tipMode==='pro'?state.tips.pro:state.tips.petty;const t=a[Math.floor(Math.random()*a.length)]||'';$('#safetyTip').value=t;state.safetyTip=t;save();render()}
$('#btnRandomTip').onclick=randomTip;
let taps=0,t=null;$('#appTitle').onclick=()=>{taps++;clearTimeout(t);t=setTimeout(()=>taps=0,600);if(taps>=5){taps=0;state.techMode=!state.techMode;save();const b=document.createElement('div');b.className='banner';b.textContent=state.techMode?'🎉 Nice Ballz Mode Activated':'Nice Ballz Mode Off';document.body.appendChild(b);setTimeout(()=>b.remove(),3000);const tm=$('#tipMode');tm.innerHTML=state.techMode?'<option value="pro">Professional</option><option value="petty">Funny/Petty</option>':'<option value="pro">Professional</option>';state.tipMode='pro'}}
function drawTipMgr(){const sel=$('#mgr-list'),wrap=$('#mgr-items');wrap.innerHTML='';const arr=sel.value==='pro'?state.tips.pro:state.tips.petty;arr.forEach((tip,i)=>{const row=document.createElement('div');row.className='mgr-row';row.innerHTML=`<input class="mgr-tip" value="${tip.replace(/"/g,'&quot;')}"> <button data-i="${i}" class="mgr-del">Delete</button>`;row.querySelector('.mgr-tip').oninput=e=>{arr[i]=e.target.value.trim();save()};row.querySelector('.mgr-del').onclick=()=>{arr.splice(i,1);save();drawTipMgr()};wrap.appendChild(row)});const o=document.querySelector('.hiddenPetty');if(o)o.style.display=state.techMode?'':''}
$('#btn-tip-manager').onclick=()=>{drawTipMgr();$('#dlg-tips').showModal()};$('#mgr-list').onchange=drawTipMgr;
$('#mgr-add').onclick=e=>{e.preventDefault();const v=$('#mgr-new').value.trim();if(!v)return;(($('#mgr-list').value==='pro')?state.tips.pro:state.tips.petty).push(v);$('#mgr-new').value='';save();drawTipMgr()};
$('#mgr-export').onclick=e=>{e.preventDefault();const d=JSON.stringify(state.tips,null,2);const u=URL.createObjectURL(new Blob([d],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='safety-tips.json';a.click();URL.revokeObjectURL(u)};
$('#mgr-import').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.pro&&d.petty){state.tips=d;save();drawTipMgr();alert('Imported tips ✔')}else alert('Invalid tips file.')}catch{alert('Invalid JSON.')}};r.readAsText(f)};
$('#btnAddTip').onclick=()=>{const t=prompt('New safety tip:');if(!t)return;const k=(state.techMode&&$('#tipMode').value==='petty')?'petty':'pro';state.tips[k].push(t.trim());state.safetyTip=t.trim();$('#safetyTip').value=t.trim();save();render()};
function tighten(s){return(s||'').replace(/\bvery\b|\bjust\b|\bkind of\b|\bbasically\b/gi,'').replace(/\s+/g,' ').trim()}
[['#shiftGroup','shiftGroup'],['#startTT','startTT'],['#endTT','endTT'],['#partsUsed','partsUsed'],['#safetyTip','safetyTip'],['#summary','summary'],['#techManual','techManual']].forEach(([s,k])=>{const el=$(s);el.value=state[k]||'';el.oninput=()=>{state[k]=el.value;save();render()}});
function techLine(){const picks=state.techsSelected.map(t=>`${t.name} (@${t.user})`);const manual=$('#techManual').value.split(',').map(s=>s.trim()).filter(Boolean);return[...picks,...manual].join(', ')}
function render(){const photoNote=state.photos.length?`\n(Attached photos: ${state.photos.length})`:'';const t=[`Shift: ${tighten(state.shiftGroup)||'(select)'}`,`Techs: ${techLine()}`,`Start of Shift TT: ${tighten(state.startTT)}`,`End of Shift TT: ${tighten(state.endTT)}`,`Parts used: ${tighten(state.partsUsed||'N/A')}`,'',`Safety Tip: ${tighten(state.safetyTip)}`,'',`Shift Summary: ${tighten(state.summary)}${photoNote}`].join('\n');$('#preview').textContent=[t,'\n_'+(state.channelNote||'#passdown')+'_'].join('\n')}render();
$('#techSearch').oninput=e=>drawTechs(e.target.value);
function copyOpen(){const m=[];if(!state.shiftGroup)m.push('Shift Group');if(!techLine())m.push('Techs');if(!tighten(state.safetyTip))m.push('Safety Tip');if(!tighten(state.summary))m.push('Shift Summary');if(m.length)return alert('Missing: '+m.join(', '));navigator.clipboard.writeText($('#preview').textContent).then(()=>{location.href='slack://';setTimeout(()=>location.href='https://slack.com/app_redirect',600);state.logs.push({ts:nowISO(),shiftGroup:state.shiftGroup,techs:techLine(),safetyTip:state.safetyTip,summary:state.summary,parts:state.partsUsed||'N/A',petty:(state.techMode&&$('#tipMode').value==='petty'),photos:state.photos.slice()});save()}).catch(()=>alert('Could not copy to clipboard.'))}
$('#btn-copy-open').onclick=copyOpen;
$('#btn-settings').onclick=()=>{$('#set-channelNote').value=state.channelNote||'#passdown';$('#set-reminder').value=state.reminderMin||120;$('#set-dark').value=state.dark||'auto';$('#dlg-settings').showModal()};
$('#btn-save-settings').onclick=e=>{e.preventDefault();state.channelNote=$('#set-channelNote').value.trim()||'#passdown';state.reminderMin=Math.max(0,Number($('#set-reminder').value||120));state.dark=$('#set-dark').value;save();applyTheme();$('#dlg-settings').close();schedRem()};
let rem=null;function schedRem(){if(rem)clearInterval(rem);const m=Number(state.reminderMin||0);if(!m)return;rem=setInterval(()=>{alert('Passdown Reminder: Note updates now.');if('vibrate'in navigator)try{navigator.vibrate(200)}catch{}},m*60*1000)}schedRem();
function weekRange(d=new Date()){const g=d.getDay(),s=new Date(d);s.setDate(d.getDate()-g);s.setHours(0,0,0,0);const e=new Date(s);e.setDate(s.getDate()+6);e.setHours(23,59,59,999);return{start:s,end:e}}
function summarize(a){const f={issues:[],parts:[],safety:[]};a.forEach(l=>{if(l.summary)f.issues.push(l.summary);if(l.parts&&l.parts!=='N/A')f.parts.push(l.parts);if(l.safetyTip)f.safety.push(l.safetyTip)});const u=x=>Array.from(new Set(x.map(s=>s.trim()).filter(Boolean)));return{issues:u(f.issues).slice(0,10),parts:u(f.parts).slice(0,10),safety:u(f.safety).slice(0,10)}}
function groupByShift(a){const g={'Front Half Days':[],'Front Half Nights':[],'Back Half Days':[],'Back Half Nights':[],'':[]};a.forEach(l=>(g[l.shiftGroup]||g['']).push(l));return g}
function buildReportHTML(r,a){const g=groupByShift(a),s=summarize(a),pad=n=>String(n).padStart(2,'0'),fmt=d=>[d.getFullYear(),pad(d.getMonth()+1),pad(d.getDate())].join('-'),title=`Passdowns ${fmt(r.start)} to ${fmt(r.end)}`,secs=Object.keys(g).filter(k=>k).map(k=>{const items=g[k].map(l=>{const imgs=(l.photos||[]).map(src=>`<img src="${src}" style="max-height:80px;border:1px solid #ccc;border-radius:6px;margin-right:6px">`).join('');return `<li><b>${l.ts.slice(0,16).replace('T',' ')}</b> — <i>${l.techs}</i><br>Safety: ${l.safetyTip}<br>Parts: ${l.parts}<br>${l.summary}<div>${imgs}</div></li>`}).join('');return `<h3>${k}</h3><ol>${items||''}</ol>`}).join('');return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title><style>body{font:14px system-ui,Segoe UI,Inter,Roboto,Arial}h1,h2,h3{margin:.4em 0}.muted{color:#555}ol{padding-left:18px}</style></head><body><h1>${title}</h1><h2>Weekly Summary</h2><p class=muted>Generated locally on your device.</p><h3>Key Issues & Notes</h3><ul>${s.issues.map(i=>`<li>${i}</li>`).join('')}</ul><h3>Parts Mentioned</h3><ul>${s.parts.map(i=>`<li>${i}</li>`).join('')}</ul><h3>Safety Highlights</h3><ul>${s.safety.map(i=>`<li>${i}</li>`).join('')}</ul><hr><h2>Full Passdown Log</h2>${secs}</body></html>`}
function openReport(r,a){const html=buildReportHTML(r,a);const u=URL.createObjectURL(new Blob([html],{type:'text/html'}));const f=$('#reportFrame');f.src=u;$('#dlg-export').showModal();$('#searchReport').oninput=e=>{const q=e.target.value.toLowerCase();const d=f.contentDocument||f.contentWindow.document;if(!d)return;d.querySelectorAll('mark._hl').forEach(m=>m.replaceWith(m.textContent));if(!q)return;const w=d.createTreeWalker(d.body,NodeFilter.SHOW_TEXT);const nodes=[];while(w.nextNode())nodes.push(w.currentNode);nodes.forEach(n=>{const t=n.nodeValue,l=t.toLowerCase(),i=l.indexOf(q);if(i>-1){const b=t.slice(0,i),m=t.slice(i,i+q.length),a=t.slice(i+q.length),frag=d.createDocumentFragment();if(b)frag.appendChild(d.createTextNode(b));const mk=d.createElement('mark');mk.className='_hl';mk.textContent=m;frag.appendChild(mk);if(a)frag.appendChild(d.createTextNode(a));n.parentNode.replaceChild(frag,n)}})};$('#btn-download-report').onclick=()=>{const a=document.createElement('a');a.href=u;a.download='Passdowns_'+r.start.toISOString().slice(0,10)+'_to_'+r.end.toISOString().slice(0,10)+'.html';a.click()}};
$('#btn-export').onclick=()=>{const {{start,end}}=weekRange(new Date());const logs=state.logs.filter(l=>{const t=new Date(l.ts);return t>=start&&t<=end});openReport({{start,end}},logs)};
function checkAutoExport(){const {{start,end}}=weekRange(new Date());const we=end.toISOString().slice(0,10);if(state.lastExportWeekEnd!==we){const pe=new Date(end);pe.setDate(end.getDate()-7);const pr=weekRange(pe);const logs=state.logs.filter(l=>{const t=new Date(l.ts);return t>=pr.start&&t<=pr.end});if(logs.length){openReport(pr,logs);state.lastExportWeekEnd=we;save()}}}
checkAutoExport();setInterval(checkAutoExport,3600000);
function bindBasics(){[['#shiftGroup','shiftGroup'],['#startTT','startTT'],['#endTT','endTT'],['#partsUsed','partsUsed'],['#safetyTip','safetyTip'],['#summary','summary'],['#techManual','techManual']].forEach(([s,k])=>{const el=$(s);el.value=state[k]||'';el.oninput=()=>{state[k]=el.value;save();render()}})}
function initTipMode(){const tm=$('#tipMode');tm.innerHTML=state.techMode?'<option value="pro">Professional</option><option value="petty">Funny/Petty</option>':'<option value="pro">Professional</option>';tm.value=state.tipMode||'pro';tm.onchange=()=>{state.tipMode=tm.value;save()}}
function autoTipOnStart(){if(!state.safetyTip){state.tipMode='pro';randomTip()}}
function drawAll(){drawTechs('');drawChips();renderPhotos();render()}bindBasics();initTipMode();autoTipOnStart();drawAll();
